///
/// NitroDeviceInfo-Swift-Cxx-Bridge.cpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#include "NitroDeviceInfo-Swift-Cxx-Bridge.hpp"

// Include C++ implementation defined types
#include "HybridDeviceInfoSpecSwift.hpp"
#include "NitroDeviceInfo-Swift-Cxx-Umbrella.hpp"
#include <NitroModules/NitroDefines.hpp>

namespace margelo::nitro::nitrodeviceinfo::bridge::swift {

  // pragma MARK: std::function<void(double /* result */)>
  Func_void_double create_Func_void_double(void* NON_NULL swiftClosureWrapper) noexcept {
    auto swiftClosure = NitroDeviceInfo::Func_void_double::fromUnsafe(swiftClosureWrapper);
    return [swiftClosure = std::move(swiftClosure)](double result) mutable -> void {
      swiftClosure.call(result);
    };
  }
  
  // pragma MARK: std::function<void(const std::exception_ptr& /* error */)>
  Func_void_std__exception_ptr create_Func_void_std__exception_ptr(void* NON_NULL swiftClosureWrapper) noexcept {
    auto swiftClosure = NitroDeviceInfo::Func_void_std__exception_ptr::fromUnsafe(swiftClosureWrapper);
    return [swiftClosure = std::move(swiftClosure)](const std::exception_ptr& error) mutable -> void {
      swiftClosure.call(error);
    };
  }
  
  // pragma MARK: std::function<void(const std::string& /* result */)>
  Func_void_std__string create_Func_void_std__string(void* NON_NULL swiftClosureWrapper) noexcept {
    auto swiftClosure = NitroDeviceInfo::Func_void_std__string::fromUnsafe(swiftClosureWrapper);
    return [swiftClosure = std::move(swiftClosure)](const std::string& result) mutable -> void {
      swiftClosure.call(result);
    };
  }
  
  // pragma MARK: std::function<void(bool /* result */)>
  Func_void_bool create_Func_void_bool(void* NON_NULL swiftClosureWrapper) noexcept {
    auto swiftClosure = NitroDeviceInfo::Func_void_bool::fromUnsafe(swiftClosureWrapper);
    return [swiftClosure = std::move(swiftClosure)](bool result) mutable -> void {
      swiftClosure.call(result);
    };
  }
  
  // pragma MARK: std::shared_ptr<HybridDeviceInfoSpec>
  std::shared_ptr<HybridDeviceInfoSpec> create_std__shared_ptr_HybridDeviceInfoSpec_(void* NON_NULL swiftUnsafePointer) noexcept {
    NitroDeviceInfo::HybridDeviceInfoSpec_cxx swiftPart = NitroDeviceInfo::HybridDeviceInfoSpec_cxx::fromUnsafe(swiftUnsafePointer);
    return std::make_shared<margelo::nitro::nitrodeviceinfo::HybridDeviceInfoSpecSwift>(swiftPart);
  }
  void* NON_NULL get_std__shared_ptr_HybridDeviceInfoSpec_(std__shared_ptr_HybridDeviceInfoSpec_ cppType) {
    std::shared_ptr<margelo::nitro::nitrodeviceinfo::HybridDeviceInfoSpecSwift> swiftWrapper = std::dynamic_pointer_cast<margelo::nitro::nitrodeviceinfo::HybridDeviceInfoSpecSwift>(cppType);
    #ifdef NITRO_DEBUG
    if (swiftWrapper == nullptr) [[unlikely]] {
      throw std::runtime_error("Class \"HybridDeviceInfoSpec\" is not implemented in Swift!");
    }
    #endif
    NitroDeviceInfo::HybridDeviceInfoSpec_cxx& swiftPart = swiftWrapper->getSwiftPart();
    return swiftPart.toUnsafe();
  }

} // namespace margelo::nitro::nitrodeviceinfo::bridge::swift
