///
/// NitroDeviceInfo-Swift-Cxx-Umbrella.hpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#pragma once

// Forward declarations of C++ defined types
// Forward declaration of `BatteryState` to properly resolve imports.
namespace margelo::nitro::nitrodeviceinfo { enum class BatteryState; }
// Forward declaration of `DeviceType` to properly resolve imports.
namespace margelo::nitro::nitrodeviceinfo { enum class DeviceType; }
// Forward declaration of `HybridDeviceInfoSpec` to properly resolve imports.
namespace margelo::nitro::nitrodeviceinfo { class HybridDeviceInfoSpec; }
// Forward declaration of `NavigationMode` to properly resolve imports.
namespace margelo::nitro::nitrodeviceinfo { enum class NavigationMode; }
// Forward declaration of `PowerState` to properly resolve imports.
namespace margelo::nitro::nitrodeviceinfo { struct PowerState; }

// Include C++ defined types
#include "BatteryState.hpp"
#include "DeviceType.hpp"
#include "HybridDeviceInfoSpec.hpp"
#include "NavigationMode.hpp"
#include "PowerState.hpp"
#include <NitroModules/Promise.hpp>
#include <NitroModules/Result.hpp>
#include <exception>
#include <memory>
#include <string>
#include <vector>

// C++ helpers for Swift
#include "NitroDeviceInfo-Swift-Cxx-Bridge.hpp"

// Common C++ types used in Swift
#include <NitroModules/ArrayBufferHolder.hpp>
#include <NitroModules/AnyMapUtils.hpp>
#include <NitroModules/RuntimeError.hpp>
#include <NitroModules/DateToChronoDate.hpp>

// Forward declarations of Swift defined types
// Forward declaration of `HybridDeviceInfoSpec_cxx` to properly resolve imports.
namespace NitroDeviceInfo { class HybridDeviceInfoSpec_cxx; }

// Include Swift defined types
#if __has_include("NitroDeviceInfo-Swift.h")
// This header is generated by Xcode/Swift on every app build.
// If it cannot be found, make sure the Swift module's name (= podspec name) is actually "NitroDeviceInfo".
#include "NitroDeviceInfo-Swift.h"
// Same as above, but used when building with frameworks (`use_frameworks`)
#elif __has_include(<NitroDeviceInfo/NitroDeviceInfo-Swift.h>)
#include <NitroDeviceInfo/NitroDeviceInfo-Swift.h>
#else
#error NitroDeviceInfo's autogenerated Swift header cannot be found! Make sure the Swift module's name (= podspec name) is actually "NitroDeviceInfo", and try building the app first.
#endif
