///
/// NitroDeviceInfoAutolinking.mm
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#import <Foundation/Foundation.h>
#import <NitroModules/HybridObjectRegistry.hpp>
#import "NitroDeviceInfo-Swift-Cxx-Umbrella.hpp"
#import <type_traits>

#include "HybridDeviceInfoSpecSwift.hpp"

@interface NitroDeviceInfoAutolinking : NSObject
@end

@implementation NitroDeviceInfoAutolinking

+ (void) load {
  using namespace margelo::nitro;
  using namespace margelo::nitro::nitrodeviceinfo;

  HybridObjectRegistry::registerHybridObjectConstructor(
    "DeviceInfo",
    []() -> std::shared_ptr<HybridObject> {
      std::shared_ptr<HybridDeviceInfoSpec> hybridObject = NitroDeviceInfo::NitroDeviceInfoAutolinking::createDeviceInfo();
      return hybridObject;
    }
  );
}

@end
