///
/// NitroDeviceInfoAutolinking.swift
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

public final class NitroDeviceInfoAutolinking {
  public typealias bridge = margelo.nitro.nitrodeviceinfo.bridge.swift

  /**
   * Creates an instance of a Swift class that implements `HybridDeviceInfoSpec`,
   * and wraps it in a Swift class that can directly interop with C++ (`HybridDeviceInfoSpec_cxx`)
   *
   * This is generated by Nitrogen and will initialize the class specified
   * in the `"autolinking"` property of `nitro.json` (in this case, `DeviceInfo`).
   */
  public static func createDeviceInfo() -> bridge.std__shared_ptr_HybridDeviceInfoSpec_ {
    let hybridObject = DeviceInfo()
    return { () -> bridge.std__shared_ptr_HybridDeviceInfoSpec_ in
      let __cxxWrapped = hybridObject.getCxxWrapper()
      return __cxxWrapped.getCxxPart()
    }()
  }
}
