///
/// HybridDeviceInfoSpecSwift.cpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#include "HybridDeviceInfoSpecSwift.hpp"

namespace margelo::nitro::nitrodeviceinfo {
} // namespace margelo::nitro::nitrodeviceinfo
