///
/// BatteryState.kt
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

package com.margelo.nitro.nitrodeviceinfo

import androidx.annotation.Keep
import com.facebook.proguard.annotations.DoNotStrip

/**
 * Represents the JavaScript enum/union "BatteryState".
 */
@DoNotStrip
@Keep
enum class BatteryState(@DoNotStrip @Keep val value: Int) {
  UNKNOWN(0),
  UNPLUGGED(1),
  CHARGING(2),
  FULL(3);

  companion object
}
