///
/// DeviceType.kt
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

package com.margelo.nitro.nitrodeviceinfo

import androidx.annotation.Keep
import com.facebook.proguard.annotations.DoNotStrip

/**
 * Represents the JavaScript enum/union "DeviceType".
 */
@DoNotStrip
@Keep
enum class DeviceType(@DoNotStrip @Keep val value: Int) {
  HANDSET(0),
  TABLET(1),
  TV(2),
  DESKTOP(3),
  GAMINGCONSOLE(4),
  UNKNOWN(5);

  companion object
}
