///
/// HybridDeviceInfoSpec.kt
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

package com.margelo.nitro.nitrodeviceinfo

import androidx.annotation.Keep
import com.facebook.jni.HybridData
import com.facebook.proguard.annotations.DoNotStrip
import com.margelo.nitro.core.Promise
import com.margelo.nitro.core.HybridObject

/**
 * A Kotlin class representing the DeviceInfo HybridObject.
 * Implement this abstract class to create Kotlin-based instances of DeviceInfo.
 */
@DoNotStrip
@Keep
@Suppress(
  "KotlinJniMissingFunction", "unused",
  "RedundantSuppression", "RedundantUnitReturnType", "SimpleRedundantLet",
  "LocalVariableName", "PropertyName", "PrivatePropertyName", "FunctionName"
)
abstract class HybridDeviceInfoSpec: HybridObject() {
  @DoNotStrip
  private var mHybridData: HybridData = initHybrid()

  init {
    super.updateNative(mHybridData)
  }

  override fun updateNative(hybridData: HybridData) {
    mHybridData = hybridData
    super.updateNative(hybridData)
  }

  // Default implementation of `HybridObject.toString()`
  override fun toString(): String {
    return "[HybridObject DeviceInfo]"
  }

  // Properties
  @get:DoNotStrip
  @get:Keep
  abstract val deviceId: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val brand: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val model: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val systemName: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val systemVersion: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val deviceType: DeviceType
  
  @get:DoNotStrip
  @get:Keep
  abstract val uniqueId: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val manufacturer: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val deviceName: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val isTablet: Boolean
  
  @get:DoNotStrip
  @get:Keep
  abstract val isEmulator: Boolean
  
  @get:DoNotStrip
  @get:Keep
  abstract val deviceYearClass: Double
  
  @get:DoNotStrip
  @get:Keep
  abstract val isCameraPresent: Boolean
  
  @get:DoNotStrip
  @get:Keep
  abstract val isPinOrFingerprintSet: Boolean
  
  @get:DoNotStrip
  @get:Keep
  abstract val isHardwareKeyStoreAvailable: Boolean
  
  @get:DoNotStrip
  @get:Keep
  abstract val isLowRamDevice: Boolean
  
  @get:DoNotStrip
  @get:Keep
  abstract val isDisplayZoomed: Boolean
  
  @get:DoNotStrip
  @get:Keep
  abstract val isLiquidGlassAvailable: Boolean
  
  @get:DoNotStrip
  @get:Keep
  abstract val totalMemory: Double
  
  @get:DoNotStrip
  @get:Keep
  abstract val maxMemory: Double
  
  @get:DoNotStrip
  @get:Keep
  abstract val totalDiskCapacity: Double
  
  @get:DoNotStrip
  @get:Keep
  abstract val startupTime: Double
  
  @get:DoNotStrip
  @get:Keep
  abstract val version: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val buildNumber: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val bundleId: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val applicationName: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val readableVersion: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val firstInstallTimeSync: Double
  
  @get:DoNotStrip
  @get:Keep
  abstract val lastUpdateTimeSync: Double
  
  @get:DoNotStrip
  @get:Keep
  abstract val carrierAllowsVOIP: Boolean
  
  @get:DoNotStrip
  @get:Keep
  abstract val carrierIsoCountryCode: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val mobileCountryCode: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val mobileNetworkCode: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val mobileNetworkOperator: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val systemLanguage: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val supportedAbis: Array<String>
  
  @get:DoNotStrip
  @get:Keep
  abstract val supported32BitAbis: Array<String>
  
  @get:DoNotStrip
  @get:Keep
  abstract val supported64BitAbis: Array<String>
  
  @get:DoNotStrip
  @get:Keep
  abstract val apiLevel: Double
  
  @get:DoNotStrip
  @get:Keep
  abstract val navigationMode: NavigationMode
  
  @get:DoNotStrip
  @get:Keep
  abstract val systemAvailableFeatures: Array<String>
  
  @get:DoNotStrip
  @get:Keep
  abstract val supportedMediaTypeList: Array<String>
  
  @get:DoNotStrip
  @get:Keep
  abstract val serialNumber: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val androidId: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val previewSdkInt: Double
  
  @get:DoNotStrip
  @get:Keep
  abstract val securityPatch: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val codename: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val incremental: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val board: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val bootloader: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val device: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val display: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val fingerprint: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val hardware: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val host: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val product: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val tags: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val type: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val baseOs: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val radioVersion: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val buildId: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val installerPackageName: String
  
  @get:DoNotStrip
  @get:Keep
  abstract val totalDiskCapacityOld: Double
  
  @get:DoNotStrip
  @get:Keep
  abstract val isMouseConnected: Boolean
  
  @get:DoNotStrip
  @get:Keep
  abstract val isKeyboardConnected: Boolean
  
  @get:DoNotStrip
  @get:Keep
  abstract val hostNames: Array<String>
  
  @get:DoNotStrip
  @get:Keep
  abstract val isTabletMode: Boolean

  // Methods
  @DoNotStrip
  @Keep
  abstract fun getHasNotch(): Boolean
  
  @DoNotStrip
  @Keep
  abstract fun getHasDynamicIsland(): Boolean
  
  @DoNotStrip
  @Keep
  abstract fun getIsLandscape(): Boolean
  
  @DoNotStrip
  @Keep
  abstract fun getBrightness(): Double
  
  @DoNotStrip
  @Keep
  abstract fun getFontScale(): Double
  
  @DoNotStrip
  @Keep
  abstract fun getUsedMemory(): Double
  
  @DoNotStrip
  @Keep
  abstract fun getFreeDiskStorage(): Double
  
  @DoNotStrip
  @Keep
  abstract fun getUptime(): Double
  
  @DoNotStrip
  @Keep
  abstract fun getBatteryLevel(): Double
  
  @DoNotStrip
  @Keep
  abstract fun getPowerState(): PowerState
  
  @DoNotStrip
  @Keep
  abstract fun getIsBatteryCharging(): Boolean
  
  @DoNotStrip
  @Keep
  abstract fun isLowBatteryLevel(threshold: Double): Boolean
  
  @DoNotStrip
  @Keep
  abstract fun getFirstInstallTime(): Promise<Double>
  
  @DoNotStrip
  @Keep
  abstract fun getLastUpdateTime(): Promise<Double>
  
  @DoNotStrip
  @Keep
  abstract fun getIpAddress(): Promise<String>
  
  @DoNotStrip
  @Keep
  abstract fun getIpAddressSync(): String
  
  @DoNotStrip
  @Keep
  abstract fun getMacAddress(): Promise<String>
  
  @DoNotStrip
  @Keep
  abstract fun getMacAddressSync(): String
  
  @DoNotStrip
  @Keep
  abstract fun getUserAgent(): Promise<String>
  
  @DoNotStrip
  @Keep
  abstract fun getIsAirplaneMode(): Boolean
  
  @DoNotStrip
  @Keep
  abstract fun getCarrier(): Promise<String>
  
  @DoNotStrip
  @Keep
  abstract fun getCarrierSync(): String
  
  @DoNotStrip
  @Keep
  abstract fun isHeadphonesConnected(): Promise<Boolean>
  
  @DoNotStrip
  @Keep
  abstract fun getIsHeadphonesConnected(): Boolean
  
  @DoNotStrip
  @Keep
  abstract fun getIsWiredHeadphonesConnected(): Boolean
  
  @DoNotStrip
  @Keep
  abstract fun getIsBluetoothHeadphonesConnected(): Boolean
  
  @DoNotStrip
  @Keep
  abstract fun isLocationEnabled(): Promise<Boolean>
  
  @DoNotStrip
  @Keep
  abstract fun getIsLocationEnabled(): Boolean
  
  @DoNotStrip
  @Keep
  abstract fun getAvailableLocationProviders(): Array<String>
  
  @DoNotStrip
  @Keep
  abstract fun getHasGms(): Boolean
  
  @DoNotStrip
  @Keep
  abstract fun getHasHms(): Boolean
  
  @DoNotStrip
  @Keep
  abstract fun hasSystemFeature(feature: String): Boolean
  
  @DoNotStrip
  @Keep
  abstract fun getDeviceToken(): Promise<String>
  
  @DoNotStrip
  @Keep
  abstract fun syncUniqueId(): Promise<String>
  
  @DoNotStrip
  @Keep
  abstract fun getInstallReferrer(): Promise<String>
  
  @DoNotStrip
  @Keep
  abstract fun isSideLoadingEnabled(): Boolean
  
  @DoNotStrip
  @Keep
  abstract fun getFreeDiskStorageOld(): Double
  
  @DoNotStrip
  @Keep
  abstract fun isDeviceCompromised(): Boolean
  
  @DoNotStrip
  @Keep
  abstract fun verifyDeviceIntegrity(): Promise<Boolean>

  private external fun initHybrid(): HybridData

  companion object {
    protected const val TAG = "HybridDeviceInfoSpec"
  }
}
