///
/// NavigationMode.kt
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

package com.margelo.nitro.nitrodeviceinfo

import androidx.annotation.Keep
import com.facebook.proguard.annotations.DoNotStrip

/**
 * Represents the JavaScript enum/union "NavigationMode".
 */
@DoNotStrip
@Keep
enum class NavigationMode(@DoNotStrip @Keep val value: Int) {
  UNKNOWN(0),
  GESTURE(1),
  BUTTONS(2),
  TWOBUTTONS(3);

  companion object
}
