///
/// nitrodeviceinfoOnLoad.kt
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

package com.margelo.nitro.nitrodeviceinfo

import android.util.Log

internal class nitrodeviceinfoOnLoad {
  companion object {
    private const val TAG = "nitrodeviceinfoOnLoad"
    private var didLoad = false
    /**
     * Initializes the native part of "nitrodeviceinfo".
     * This method is idempotent and can be called more than once.
     */
    @JvmStatic
    fun initializeNative() {
      if (didLoad) return
      try {
        Log.i(TAG, "Loading nitrodeviceinfo C++ library...")
        System.loadLibrary("nitrodeviceinfo")
        Log.i(TAG, "Successfully loaded nitrodeviceinfo C++ library!")
        didLoad = true
      } catch (e: Error) {
        Log.e(TAG, "Failed to load nitrodeviceinfo C++ library! Is it properly installed and linked? " +
                    "Is the name correct? (see `CMakeLists.txt`, at `add_library(...)`)", e)
        throw e
      }
    }
  }
}
