///
/// PowerState.kt
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

package com.margelo.nitro.nitrodeviceinfo

import androidx.annotation.Keep
import com.facebook.proguard.annotations.DoNotStrip


/**
 * Represents the JavaScript object/struct "PowerState".
 */
@DoNotStrip
@Keep
data class PowerState(
  @DoNotStrip
  @Keep
  val batteryLevel: Double,
  @DoNotStrip
  @Keep
  val batteryState: BatteryState,
  @DoNotStrip
  @Keep
  val lowPowerMode: Boolean
) {
  /* primary constructor */

  companion object {
    /**
     * Constructor called from C++
     */
    @DoNotStrip
    @Keep
    @Suppress("unused")
    @JvmStatic
    private fun fromCpp(batteryLevel: Double, batteryState: BatteryState, lowPowerMode: Boolean): PowerState {
      return PowerState(batteryLevel, batteryState, lowPowerMode)
    }
  }
}
