///
/// JBatteryState.hpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#pragma once

#include <fbjni/fbjni.h>
#include "BatteryState.hpp"

namespace margelo::nitro::nitrodeviceinfo {

  using namespace facebook;

  /**
   * The C++ JNI bridge between the C++ enum "BatteryState" and the the Kotlin enum "BatteryState".
   */
  struct JBatteryState final: public jni::JavaClass<JBatteryState> {
  public:
    static auto constexpr kJavaDescriptor = "Lcom/margelo/nitro/nitrodeviceinfo/BatteryState;";

  public:
    /**
     * Convert this Java/Kotlin-based enum to the C++ enum BatteryState.
     */
    [[maybe_unused]]
    [[nodiscard]]
    BatteryState toCpp() const {
      static const auto clazz = javaClassStatic();
      static const auto fieldOrdinal = clazz->getField<int>("value");
      int ordinal = this->getFieldValue(fieldOrdinal);
      return static_cast<BatteryState>(ordinal);
    }

  public:
    /**
     * Create a Java/Kotlin-based enum with the given C++ enum's value.
     */
    [[maybe_unused]]
    static jni::alias_ref<JBatteryState> fromCpp(BatteryState value) {
      static const auto clazz = javaClassStatic();
      switch (value) {
        case BatteryState::UNKNOWN:
          static const auto fieldUNKNOWN = clazz->getStaticField<JBatteryState>("UNKNOWN");
          return clazz->getStaticFieldValue(fieldUNKNOWN);
        case BatteryState::UNPLUGGED:
          static const auto fieldUNPLUGGED = clazz->getStaticField<JBatteryState>("UNPLUGGED");
          return clazz->getStaticFieldValue(fieldUNPLUGGED);
        case BatteryState::CHARGING:
          static const auto fieldCHARGING = clazz->getStaticField<JBatteryState>("CHARGING");
          return clazz->getStaticFieldValue(fieldCHARGING);
        case BatteryState::FULL:
          static const auto fieldFULL = clazz->getStaticField<JBatteryState>("FULL");
          return clazz->getStaticFieldValue(fieldFULL);
        default:
          std::string stringValue = std::to_string(static_cast<int>(value));
          throw std::invalid_argument("Invalid enum value (" + stringValue + "!");
      }
    }
  };

} // namespace margelo::nitro::nitrodeviceinfo
