///
/// JDeviceType.hpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#pragma once

#include <fbjni/fbjni.h>
#include "DeviceType.hpp"

namespace margelo::nitro::nitrodeviceinfo {

  using namespace facebook;

  /**
   * The C++ JNI bridge between the C++ enum "DeviceType" and the the Kotlin enum "DeviceType".
   */
  struct JDeviceType final: public jni::JavaClass<JDeviceType> {
  public:
    static auto constexpr kJavaDescriptor = "Lcom/margelo/nitro/nitrodeviceinfo/DeviceType;";

  public:
    /**
     * Convert this Java/Kotlin-based enum to the C++ enum DeviceType.
     */
    [[maybe_unused]]
    [[nodiscard]]
    DeviceType toCpp() const {
      static const auto clazz = javaClassStatic();
      static const auto fieldOrdinal = clazz->getField<int>("value");
      int ordinal = this->getFieldValue(fieldOrdinal);
      return static_cast<DeviceType>(ordinal);
    }

  public:
    /**
     * Create a Java/Kotlin-based enum with the given C++ enum's value.
     */
    [[maybe_unused]]
    static jni::alias_ref<JDeviceType> fromCpp(DeviceType value) {
      static const auto clazz = javaClassStatic();
      switch (value) {
        case DeviceType::HANDSET:
          static const auto fieldHANDSET = clazz->getStaticField<JDeviceType>("HANDSET");
          return clazz->getStaticFieldValue(fieldHANDSET);
        case DeviceType::TABLET:
          static const auto fieldTABLET = clazz->getStaticField<JDeviceType>("TABLET");
          return clazz->getStaticFieldValue(fieldTABLET);
        case DeviceType::TV:
          static const auto fieldTV = clazz->getStaticField<JDeviceType>("TV");
          return clazz->getStaticFieldValue(fieldTV);
        case DeviceType::DESKTOP:
          static const auto fieldDESKTOP = clazz->getStaticField<JDeviceType>("DESKTOP");
          return clazz->getStaticFieldValue(fieldDESKTOP);
        case DeviceType::GAMINGCONSOLE:
          static const auto fieldGAMINGCONSOLE = clazz->getStaticField<JDeviceType>("GAMINGCONSOLE");
          return clazz->getStaticFieldValue(fieldGAMINGCONSOLE);
        case DeviceType::UNKNOWN:
          static const auto fieldUNKNOWN = clazz->getStaticField<JDeviceType>("UNKNOWN");
          return clazz->getStaticFieldValue(fieldUNKNOWN);
        default:
          std::string stringValue = std::to_string(static_cast<int>(value));
          throw std::invalid_argument("Invalid enum value (" + stringValue + "!");
      }
    }
  };

} // namespace margelo::nitro::nitrodeviceinfo
