///
/// HybridDeviceInfoSpec.hpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#pragma once

#include <NitroModules/JHybridObject.hpp>
#include <fbjni/fbjni.h>
#include "HybridDeviceInfoSpec.hpp"




namespace margelo::nitro::nitrodeviceinfo {

  using namespace facebook;

  class JHybridDeviceInfoSpec: public jni::HybridClass<JHybridDeviceInfoSpec, JHybridObject>,
                               public virtual HybridDeviceInfoSpec {
  public:
    static auto constexpr kJavaDescriptor = "Lcom/margelo/nitro/nitrodeviceinfo/HybridDeviceInfoSpec;";
    static jni::local_ref<jhybriddata> initHybrid(jni::alias_ref<jhybridobject> jThis);
    static void registerNatives();

  protected:
    // C++ constructor (called from Java via `initHybrid()`)
    explicit JHybridDeviceInfoSpec(jni::alias_ref<jhybridobject> jThis) :
      HybridObject(HybridDeviceInfoSpec::TAG),
      HybridBase(jThis),
      _javaPart(jni::make_global(jThis)) {}

  public:
    ~JHybridDeviceInfoSpec() override {
      // Hermes GC can destroy JS objects on a non-JNI Thread.
      jni::ThreadScope::WithClassLoader([&] { _javaPart.reset(); });
    }

  public:
    size_t getExternalMemorySize() noexcept override;
    bool equals(const std::shared_ptr<HybridObject>& other) override;
    void dispose() noexcept override;
    std::string toString() override;

  public:
    inline const jni::global_ref<JHybridDeviceInfoSpec::javaobject>& getJavaPart() const noexcept {
      return _javaPart;
    }

  public:
    // Properties
    std::string getDeviceId() override;
    std::string getBrand() override;
    std::string getModel() override;
    std::string getSystemName() override;
    std::string getSystemVersion() override;
    DeviceType getDeviceType() override;
    std::string getUniqueId() override;
    std::string getManufacturer() override;
    std::string getDeviceName() override;
    bool getIsTablet() override;
    bool getIsEmulator() override;
    double getDeviceYearClass() override;
    bool getIsCameraPresent() override;
    bool getIsPinOrFingerprintSet() override;
    bool getIsHardwareKeyStoreAvailable() override;
    bool getIsLowRamDevice() override;
    bool getIsDisplayZoomed() override;
    bool getIsLiquidGlassAvailable() override;
    double getTotalMemory() override;
    double getMaxMemory() override;
    double getTotalDiskCapacity() override;
    double getStartupTime() override;
    std::string getVersion() override;
    std::string getBuildNumber() override;
    std::string getBundleId() override;
    std::string getApplicationName() override;
    std::string getReadableVersion() override;
    double getFirstInstallTimeSync() override;
    double getLastUpdateTimeSync() override;
    bool getCarrierAllowsVOIP() override;
    std::string getCarrierIsoCountryCode() override;
    std::string getMobileCountryCode() override;
    std::string getMobileNetworkCode() override;
    std::string getMobileNetworkOperator() override;
    std::string getSystemLanguage() override;
    std::vector<std::string> getSupportedAbis() override;
    std::vector<std::string> getSupported32BitAbis() override;
    std::vector<std::string> getSupported64BitAbis() override;
    double getApiLevel() override;
    NavigationMode getNavigationMode() override;
    std::vector<std::string> getSystemAvailableFeatures() override;
    std::vector<std::string> getSupportedMediaTypeList() override;
    std::string getSerialNumber() override;
    std::string getAndroidId() override;
    double getPreviewSdkInt() override;
    std::string getSecurityPatch() override;
    std::string getCodename() override;
    std::string getIncremental() override;
    std::string getBoard() override;
    std::string getBootloader() override;
    std::string getDevice() override;
    std::string getDisplay() override;
    std::string getFingerprint() override;
    std::string getHardware() override;
    std::string getHost() override;
    std::string getProduct() override;
    std::string getTags() override;
    std::string getType() override;
    std::string getBaseOs() override;
    std::string getRadioVersion() override;
    std::string getBuildId() override;
    std::string getInstallerPackageName() override;
    double getTotalDiskCapacityOld() override;
    bool getIsMouseConnected() override;
    bool getIsKeyboardConnected() override;
    std::vector<std::string> getHostNames() override;
    bool getIsTabletMode() override;

  public:
    // Methods
    bool getHasNotch() override;
    bool getHasDynamicIsland() override;
    bool getIsLandscape() override;
    double getBrightness() override;
    double getFontScale() override;
    double getUsedMemory() override;
    double getFreeDiskStorage() override;
    double getUptime() override;
    double getBatteryLevel() override;
    PowerState getPowerState() override;
    bool getIsBatteryCharging() override;
    bool isLowBatteryLevel(double threshold) override;
    std::shared_ptr<Promise<double>> getFirstInstallTime() override;
    std::shared_ptr<Promise<double>> getLastUpdateTime() override;
    std::shared_ptr<Promise<std::string>> getIpAddress() override;
    std::string getIpAddressSync() override;
    std::shared_ptr<Promise<std::string>> getMacAddress() override;
    std::string getMacAddressSync() override;
    std::shared_ptr<Promise<std::string>> getUserAgent() override;
    bool getIsAirplaneMode() override;
    std::shared_ptr<Promise<std::string>> getCarrier() override;
    std::string getCarrierSync() override;
    std::shared_ptr<Promise<bool>> isHeadphonesConnected() override;
    bool getIsHeadphonesConnected() override;
    bool getIsWiredHeadphonesConnected() override;
    bool getIsBluetoothHeadphonesConnected() override;
    std::shared_ptr<Promise<bool>> isLocationEnabled() override;
    bool getIsLocationEnabled() override;
    std::vector<std::string> getAvailableLocationProviders() override;
    bool getHasGms() override;
    bool getHasHms() override;
    bool hasSystemFeature(const std::string& feature) override;
    std::shared_ptr<Promise<std::string>> getDeviceToken() override;
    std::shared_ptr<Promise<std::string>> syncUniqueId() override;
    std::shared_ptr<Promise<std::string>> getInstallReferrer() override;
    bool isSideLoadingEnabled() override;
    double getFreeDiskStorageOld() override;
    bool isDeviceCompromised() override;
    std::shared_ptr<Promise<bool>> verifyDeviceIntegrity() override;

  private:
    friend HybridBase;
    using HybridBase::HybridBase;
    jni::global_ref<JHybridDeviceInfoSpec::javaobject> _javaPart;
  };

} // namespace margelo::nitro::nitrodeviceinfo
