///
/// JNavigationMode.hpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#pragma once

#include <fbjni/fbjni.h>
#include "NavigationMode.hpp"

namespace margelo::nitro::nitrodeviceinfo {

  using namespace facebook;

  /**
   * The C++ JNI bridge between the C++ enum "NavigationMode" and the the Kotlin enum "NavigationMode".
   */
  struct JNavigationMode final: public jni::JavaClass<JNavigationMode> {
  public:
    static auto constexpr kJavaDescriptor = "Lcom/margelo/nitro/nitrodeviceinfo/NavigationMode;";

  public:
    /**
     * Convert this Java/Kotlin-based enum to the C++ enum NavigationMode.
     */
    [[maybe_unused]]
    [[nodiscard]]
    NavigationMode toCpp() const {
      static const auto clazz = javaClassStatic();
      static const auto fieldOrdinal = clazz->getField<int>("value");
      int ordinal = this->getFieldValue(fieldOrdinal);
      return static_cast<NavigationMode>(ordinal);
    }

  public:
    /**
     * Create a Java/Kotlin-based enum with the given C++ enum's value.
     */
    [[maybe_unused]]
    static jni::alias_ref<JNavigationMode> fromCpp(NavigationMode value) {
      static const auto clazz = javaClassStatic();
      switch (value) {
        case NavigationMode::UNKNOWN:
          static const auto fieldUNKNOWN = clazz->getStaticField<JNavigationMode>("UNKNOWN");
          return clazz->getStaticFieldValue(fieldUNKNOWN);
        case NavigationMode::GESTURE:
          static const auto fieldGESTURE = clazz->getStaticField<JNavigationMode>("GESTURE");
          return clazz->getStaticFieldValue(fieldGESTURE);
        case NavigationMode::BUTTONS:
          static const auto fieldBUTTONS = clazz->getStaticField<JNavigationMode>("BUTTONS");
          return clazz->getStaticFieldValue(fieldBUTTONS);
        case NavigationMode::TWOBUTTONS:
          static const auto fieldTWOBUTTONS = clazz->getStaticField<JNavigationMode>("TWOBUTTONS");
          return clazz->getStaticFieldValue(fieldTWOBUTTONS);
        default:
          std::string stringValue = std::to_string(static_cast<int>(value));
          throw std::invalid_argument("Invalid enum value (" + stringValue + "!");
      }
    }
  };

} // namespace margelo::nitro::nitrodeviceinfo
