///
/// nitrodeviceinfoOnLoad.cpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#ifndef BUILDING_NITRODEVICEINFO_WITH_GENERATED_CMAKE_PROJECT
#error nitrodeviceinfoOnLoad.cpp is not being built with the autogenerated CMakeLists.txt project. Is a different CMakeLists.txt building this?
#endif

#include "nitrodeviceinfoOnLoad.hpp"

#include <jni.h>
#include <fbjni/fbjni.h>
#include <NitroModules/HybridObjectRegistry.hpp>

#include "JHybridDeviceInfoSpec.hpp"
#include <NitroModules/DefaultConstructableObject.hpp>

namespace margelo::nitro::nitrodeviceinfo {

int initialize(JavaVM* vm) {
  using namespace margelo::nitro;
  using namespace margelo::nitro::nitrodeviceinfo;
  using namespace facebook;

  return facebook::jni::initialize(vm, [] {
    // Register native JNI methods
    margelo::nitro::nitrodeviceinfo::JHybridDeviceInfoSpec::registerNatives();

    // Register Nitro Hybrid Objects
    HybridObjectRegistry::registerHybridObjectConstructor(
      "DeviceInfo",
      []() -> std::shared_ptr<HybridObject> {
        static DefaultConstructableObject<JHybridDeviceInfoSpec::javaobject> object("com/margelo/nitro/nitrodeviceinfo/DeviceInfo");
        auto instance = object.create();
        return instance->cthis()->shared();
      }
    );
  });
}

} // namespace margelo::nitro::nitrodeviceinfo
