///
/// HybridDeviceInfoSpec_cxx.swift
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

import Foundation
import NitroModules

/**
 * A class implementation that bridges HybridDeviceInfoSpec over to C++.
 * In C++, we cannot use Swift protocols - so we need to wrap it in a class to make it strongly defined.
 *
 * Also, some Swift types need to be bridged with special handling:
 * - Enums need to be wrapped in Structs, otherwise they cannot be accessed bi-directionally (Swift bug: https://github.com/swiftlang/swift/issues/75330)
 * - Other HybridObjects need to be wrapped/unwrapped from the Swift TCxx wrapper
 * - Throwing methods need to be wrapped with a Result<T, Error> type, as exceptions cannot be propagated to C++
 */
open class HybridDeviceInfoSpec_cxx {
  /**
   * The Swift <> C++ bridge's namespace (`margelo::nitro::nitrodeviceinfo::bridge::swift`)
   * from `NitroDeviceInfo-Swift-Cxx-Bridge.hpp`.
   * This contains specialized C++ templates, and C++ helper functions that can be accessed from Swift.
   */
  public typealias bridge = margelo.nitro.nitrodeviceinfo.bridge.swift

  /**
   * Holds an instance of the `HybridDeviceInfoSpec` Swift protocol.
   */
  private var __implementation: any HybridDeviceInfoSpec

  /**
   * Holds a weak pointer to the C++ class that wraps the Swift class.
   */
  private var __cxxPart: bridge.std__weak_ptr_HybridDeviceInfoSpec_

  /**
   * Create a new `HybridDeviceInfoSpec_cxx` that wraps the given `HybridDeviceInfoSpec`.
   * All properties and methods bridge to C++ types.
   */
  public init(_ implementation: any HybridDeviceInfoSpec) {
    self.__implementation = implementation
    self.__cxxPart = .init()
    /* no base class */
  }

  /**
   * Get the actual `HybridDeviceInfoSpec` instance this class wraps.
   */
  @inline(__always)
  public func getHybridDeviceInfoSpec() -> any HybridDeviceInfoSpec {
    return __implementation
  }

  /**
   * Casts this instance to a retained unsafe raw pointer.
   * This acquires one additional strong reference on the object!
   */
  public func toUnsafe() -> UnsafeMutableRawPointer {
    return Unmanaged.passRetained(self).toOpaque()
  }

  /**
   * Casts an unsafe pointer to a `HybridDeviceInfoSpec_cxx`.
   * The pointer has to be a retained opaque `Unmanaged<HybridDeviceInfoSpec_cxx>`.
   * This removes one strong reference from the object!
   */
  public class func fromUnsafe(_ pointer: UnsafeMutableRawPointer) -> HybridDeviceInfoSpec_cxx {
    return Unmanaged<HybridDeviceInfoSpec_cxx>.fromOpaque(pointer).takeRetainedValue()
  }

  /**
   * Gets (or creates) the C++ part of this Hybrid Object.
   * The C++ part is a `std::shared_ptr<HybridDeviceInfoSpec>`.
   */
  public func getCxxPart() -> bridge.std__shared_ptr_HybridDeviceInfoSpec_ {
    let cachedCxxPart = self.__cxxPart.lock()
    if Bool(fromCxx: cachedCxxPart) {
      return cachedCxxPart
    } else {
      let newCxxPart = bridge.create_std__shared_ptr_HybridDeviceInfoSpec_(self.toUnsafe())
      __cxxPart = bridge.weakify_std__shared_ptr_HybridDeviceInfoSpec_(newCxxPart)
      return newCxxPart
    }
  }

  

  /**
   * Get the memory size of the Swift class (plus size of any other allocations)
   * so the JS VM can properly track it and garbage-collect the JS object if needed.
   */
  @inline(__always)
  public var memorySize: Int {
    return MemoryHelper.getSizeOf(self.__implementation) + self.__implementation.memorySize
  }

  /**
   * Compares this object with the given [other] object for reference equality.
   */
  @inline(__always)
  public func equals(other: HybridDeviceInfoSpec_cxx) -> Bool {
    return self.__implementation === other.__implementation
  }

  /**
   * Call dispose() on the Swift class.
   * This _may_ be called manually from JS.
   */
  @inline(__always)
  public func dispose() {
    self.__implementation.dispose()
  }

  /**
   * Call toString() on the Swift class.
   */
  @inline(__always)
  public func toString() -> String {
    return self.__implementation.toString()
  }

  // Properties
  public final var deviceId: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.deviceId)
    }
  }
  
  public final var brand: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.brand)
    }
  }
  
  public final var model: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.model)
    }
  }
  
  public final var systemName: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.systemName)
    }
  }
  
  public final var systemVersion: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.systemVersion)
    }
  }
  
  public final var deviceType: Int32 {
    @inline(__always)
    get {
      return self.__implementation.deviceType.rawValue
    }
  }
  
  public final var uniqueId: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.uniqueId)
    }
  }
  
  public final var manufacturer: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.manufacturer)
    }
  }
  
  public final var deviceName: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.deviceName)
    }
  }
  
  public final var isTablet: Bool {
    @inline(__always)
    get {
      return self.__implementation.isTablet
    }
  }
  
  public final var isEmulator: Bool {
    @inline(__always)
    get {
      return self.__implementation.isEmulator
    }
  }
  
  public final var deviceYearClass: Double {
    @inline(__always)
    get {
      return self.__implementation.deviceYearClass
    }
  }
  
  public final var isCameraPresent: Bool {
    @inline(__always)
    get {
      return self.__implementation.isCameraPresent
    }
  }
  
  public final var isPinOrFingerprintSet: Bool {
    @inline(__always)
    get {
      return self.__implementation.isPinOrFingerprintSet
    }
  }
  
  public final var isHardwareKeyStoreAvailable: Bool {
    @inline(__always)
    get {
      return self.__implementation.isHardwareKeyStoreAvailable
    }
  }
  
  public final var isLowRamDevice: Bool {
    @inline(__always)
    get {
      return self.__implementation.isLowRamDevice
    }
  }
  
  public final var isDisplayZoomed: Bool {
    @inline(__always)
    get {
      return self.__implementation.isDisplayZoomed
    }
  }
  
  public final var isLiquidGlassAvailable: Bool {
    @inline(__always)
    get {
      return self.__implementation.isLiquidGlassAvailable
    }
  }
  
  public final var totalMemory: Double {
    @inline(__always)
    get {
      return self.__implementation.totalMemory
    }
  }
  
  public final var maxMemory: Double {
    @inline(__always)
    get {
      return self.__implementation.maxMemory
    }
  }
  
  public final var totalDiskCapacity: Double {
    @inline(__always)
    get {
      return self.__implementation.totalDiskCapacity
    }
  }
  
  public final var startupTime: Double {
    @inline(__always)
    get {
      return self.__implementation.startupTime
    }
  }
  
  public final var version: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.version)
    }
  }
  
  public final var buildNumber: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.buildNumber)
    }
  }
  
  public final var bundleId: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.bundleId)
    }
  }
  
  public final var applicationName: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.applicationName)
    }
  }
  
  public final var readableVersion: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.readableVersion)
    }
  }
  
  public final var firstInstallTimeSync: Double {
    @inline(__always)
    get {
      return self.__implementation.firstInstallTimeSync
    }
  }
  
  public final var lastUpdateTimeSync: Double {
    @inline(__always)
    get {
      return self.__implementation.lastUpdateTimeSync
    }
  }
  
  public final var carrierAllowsVOIP: Bool {
    @inline(__always)
    get {
      return self.__implementation.carrierAllowsVOIP
    }
  }
  
  public final var carrierIsoCountryCode: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.carrierIsoCountryCode)
    }
  }
  
  public final var mobileCountryCode: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.mobileCountryCode)
    }
  }
  
  public final var mobileNetworkCode: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.mobileNetworkCode)
    }
  }
  
  public final var mobileNetworkOperator: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.mobileNetworkOperator)
    }
  }
  
  public final var systemLanguage: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.systemLanguage)
    }
  }
  
  public final var supportedAbis: bridge.std__vector_std__string_ {
    @inline(__always)
    get {
      return { () -> bridge.std__vector_std__string_ in
        var __vector = bridge.create_std__vector_std__string_(self.__implementation.supportedAbis.count)
        for __item in self.__implementation.supportedAbis {
          __vector.push_back(std.string(__item))
        }
        return __vector
      }()
    }
  }
  
  public final var supported32BitAbis: bridge.std__vector_std__string_ {
    @inline(__always)
    get {
      return { () -> bridge.std__vector_std__string_ in
        var __vector = bridge.create_std__vector_std__string_(self.__implementation.supported32BitAbis.count)
        for __item in self.__implementation.supported32BitAbis {
          __vector.push_back(std.string(__item))
        }
        return __vector
      }()
    }
  }
  
  public final var supported64BitAbis: bridge.std__vector_std__string_ {
    @inline(__always)
    get {
      return { () -> bridge.std__vector_std__string_ in
        var __vector = bridge.create_std__vector_std__string_(self.__implementation.supported64BitAbis.count)
        for __item in self.__implementation.supported64BitAbis {
          __vector.push_back(std.string(__item))
        }
        return __vector
      }()
    }
  }
  
  public final var apiLevel: Double {
    @inline(__always)
    get {
      return self.__implementation.apiLevel
    }
  }
  
  public final var navigationMode: Int32 {
    @inline(__always)
    get {
      return self.__implementation.navigationMode.rawValue
    }
  }
  
  public final var systemAvailableFeatures: bridge.std__vector_std__string_ {
    @inline(__always)
    get {
      return { () -> bridge.std__vector_std__string_ in
        var __vector = bridge.create_std__vector_std__string_(self.__implementation.systemAvailableFeatures.count)
        for __item in self.__implementation.systemAvailableFeatures {
          __vector.push_back(std.string(__item))
        }
        return __vector
      }()
    }
  }
  
  public final var supportedMediaTypeList: bridge.std__vector_std__string_ {
    @inline(__always)
    get {
      return { () -> bridge.std__vector_std__string_ in
        var __vector = bridge.create_std__vector_std__string_(self.__implementation.supportedMediaTypeList.count)
        for __item in self.__implementation.supportedMediaTypeList {
          __vector.push_back(std.string(__item))
        }
        return __vector
      }()
    }
  }
  
  public final var serialNumber: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.serialNumber)
    }
  }
  
  public final var androidId: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.androidId)
    }
  }
  
  public final var previewSdkInt: Double {
    @inline(__always)
    get {
      return self.__implementation.previewSdkInt
    }
  }
  
  public final var securityPatch: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.securityPatch)
    }
  }
  
  public final var codename: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.codename)
    }
  }
  
  public final var incremental: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.incremental)
    }
  }
  
  public final var board: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.board)
    }
  }
  
  public final var bootloader: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.bootloader)
    }
  }
  
  public final var device: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.device)
    }
  }
  
  public final var display: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.display)
    }
  }
  
  public final var fingerprint: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.fingerprint)
    }
  }
  
  public final var hardware: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.hardware)
    }
  }
  
  public final var host: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.host)
    }
  }
  
  public final var product: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.product)
    }
  }
  
  public final var tags: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.tags)
    }
  }
  
  public final var type: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.type)
    }
  }
  
  public final var baseOs: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.baseOs)
    }
  }
  
  public final var radioVersion: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.radioVersion)
    }
  }
  
  public final var buildId: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.buildId)
    }
  }
  
  public final var installerPackageName: std.string {
    @inline(__always)
    get {
      return std.string(self.__implementation.installerPackageName)
    }
  }
  
  public final var totalDiskCapacityOld: Double {
    @inline(__always)
    get {
      return self.__implementation.totalDiskCapacityOld
    }
  }
  
  public final var isMouseConnected: Bool {
    @inline(__always)
    get {
      return self.__implementation.isMouseConnected
    }
  }
  
  public final var isKeyboardConnected: Bool {
    @inline(__always)
    get {
      return self.__implementation.isKeyboardConnected
    }
  }
  
  public final var hostNames: bridge.std__vector_std__string_ {
    @inline(__always)
    get {
      return { () -> bridge.std__vector_std__string_ in
        var __vector = bridge.create_std__vector_std__string_(self.__implementation.hostNames.count)
        for __item in self.__implementation.hostNames {
          __vector.push_back(std.string(__item))
        }
        return __vector
      }()
    }
  }
  
  public final var isTabletMode: Bool {
    @inline(__always)
    get {
      return self.__implementation.isTabletMode
    }
  }

  // Methods
  @inline(__always)
  public final func getHasNotch() -> bridge.Result_bool_ {
    do {
      let __result = try self.__implementation.getHasNotch()
      let __resultCpp = __result
      return bridge.create_Result_bool_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_bool_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getHasDynamicIsland() -> bridge.Result_bool_ {
    do {
      let __result = try self.__implementation.getHasDynamicIsland()
      let __resultCpp = __result
      return bridge.create_Result_bool_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_bool_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getIsLandscape() -> bridge.Result_bool_ {
    do {
      let __result = try self.__implementation.getIsLandscape()
      let __resultCpp = __result
      return bridge.create_Result_bool_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_bool_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getBrightness() -> bridge.Result_double_ {
    do {
      let __result = try self.__implementation.getBrightness()
      let __resultCpp = __result
      return bridge.create_Result_double_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_double_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getFontScale() -> bridge.Result_double_ {
    do {
      let __result = try self.__implementation.getFontScale()
      let __resultCpp = __result
      return bridge.create_Result_double_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_double_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getUsedMemory() -> bridge.Result_double_ {
    do {
      let __result = try self.__implementation.getUsedMemory()
      let __resultCpp = __result
      return bridge.create_Result_double_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_double_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getFreeDiskStorage() -> bridge.Result_double_ {
    do {
      let __result = try self.__implementation.getFreeDiskStorage()
      let __resultCpp = __result
      return bridge.create_Result_double_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_double_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getUptime() -> bridge.Result_double_ {
    do {
      let __result = try self.__implementation.getUptime()
      let __resultCpp = __result
      return bridge.create_Result_double_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_double_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getBatteryLevel() -> bridge.Result_double_ {
    do {
      let __result = try self.__implementation.getBatteryLevel()
      let __resultCpp = __result
      return bridge.create_Result_double_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_double_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getPowerState() -> bridge.Result_PowerState_ {
    do {
      let __result = try self.__implementation.getPowerState()
      let __resultCpp = __result
      return bridge.create_Result_PowerState_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_PowerState_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getIsBatteryCharging() -> bridge.Result_bool_ {
    do {
      let __result = try self.__implementation.getIsBatteryCharging()
      let __resultCpp = __result
      return bridge.create_Result_bool_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_bool_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func isLowBatteryLevel(threshold: Double) -> bridge.Result_bool_ {
    do {
      let __result = try self.__implementation.isLowBatteryLevel(threshold: threshold)
      let __resultCpp = __result
      return bridge.create_Result_bool_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_bool_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getFirstInstallTime() -> bridge.Result_std__shared_ptr_Promise_double___ {
    do {
      let __result = try self.__implementation.getFirstInstallTime()
      let __resultCpp = { () -> bridge.std__shared_ptr_Promise_double__ in
        let __promise = bridge.create_std__shared_ptr_Promise_double__()
        let __promiseHolder = bridge.wrap_std__shared_ptr_Promise_double__(__promise)
        __result
          .then({ __result in __promiseHolder.resolve(__result) })
          .catch({ __error in __promiseHolder.reject(__error.toCpp()) })
        return __promise
      }()
      return bridge.create_Result_std__shared_ptr_Promise_double___(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_std__shared_ptr_Promise_double___(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getLastUpdateTime() -> bridge.Result_std__shared_ptr_Promise_double___ {
    do {
      let __result = try self.__implementation.getLastUpdateTime()
      let __resultCpp = { () -> bridge.std__shared_ptr_Promise_double__ in
        let __promise = bridge.create_std__shared_ptr_Promise_double__()
        let __promiseHolder = bridge.wrap_std__shared_ptr_Promise_double__(__promise)
        __result
          .then({ __result in __promiseHolder.resolve(__result) })
          .catch({ __error in __promiseHolder.reject(__error.toCpp()) })
        return __promise
      }()
      return bridge.create_Result_std__shared_ptr_Promise_double___(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_std__shared_ptr_Promise_double___(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getIpAddress() -> bridge.Result_std__shared_ptr_Promise_std__string___ {
    do {
      let __result = try self.__implementation.getIpAddress()
      let __resultCpp = { () -> bridge.std__shared_ptr_Promise_std__string__ in
        let __promise = bridge.create_std__shared_ptr_Promise_std__string__()
        let __promiseHolder = bridge.wrap_std__shared_ptr_Promise_std__string__(__promise)
        __result
          .then({ __result in __promiseHolder.resolve(std.string(__result)) })
          .catch({ __error in __promiseHolder.reject(__error.toCpp()) })
        return __promise
      }()
      return bridge.create_Result_std__shared_ptr_Promise_std__string___(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_std__shared_ptr_Promise_std__string___(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getIpAddressSync() -> bridge.Result_std__string_ {
    do {
      let __result = try self.__implementation.getIpAddressSync()
      let __resultCpp = std.string(__result)
      return bridge.create_Result_std__string_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_std__string_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getMacAddress() -> bridge.Result_std__shared_ptr_Promise_std__string___ {
    do {
      let __result = try self.__implementation.getMacAddress()
      let __resultCpp = { () -> bridge.std__shared_ptr_Promise_std__string__ in
        let __promise = bridge.create_std__shared_ptr_Promise_std__string__()
        let __promiseHolder = bridge.wrap_std__shared_ptr_Promise_std__string__(__promise)
        __result
          .then({ __result in __promiseHolder.resolve(std.string(__result)) })
          .catch({ __error in __promiseHolder.reject(__error.toCpp()) })
        return __promise
      }()
      return bridge.create_Result_std__shared_ptr_Promise_std__string___(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_std__shared_ptr_Promise_std__string___(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getMacAddressSync() -> bridge.Result_std__string_ {
    do {
      let __result = try self.__implementation.getMacAddressSync()
      let __resultCpp = std.string(__result)
      return bridge.create_Result_std__string_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_std__string_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getUserAgent() -> bridge.Result_std__shared_ptr_Promise_std__string___ {
    do {
      let __result = try self.__implementation.getUserAgent()
      let __resultCpp = { () -> bridge.std__shared_ptr_Promise_std__string__ in
        let __promise = bridge.create_std__shared_ptr_Promise_std__string__()
        let __promiseHolder = bridge.wrap_std__shared_ptr_Promise_std__string__(__promise)
        __result
          .then({ __result in __promiseHolder.resolve(std.string(__result)) })
          .catch({ __error in __promiseHolder.reject(__error.toCpp()) })
        return __promise
      }()
      return bridge.create_Result_std__shared_ptr_Promise_std__string___(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_std__shared_ptr_Promise_std__string___(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getIsAirplaneMode() -> bridge.Result_bool_ {
    do {
      let __result = try self.__implementation.getIsAirplaneMode()
      let __resultCpp = __result
      return bridge.create_Result_bool_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_bool_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getCarrier() -> bridge.Result_std__shared_ptr_Promise_std__string___ {
    do {
      let __result = try self.__implementation.getCarrier()
      let __resultCpp = { () -> bridge.std__shared_ptr_Promise_std__string__ in
        let __promise = bridge.create_std__shared_ptr_Promise_std__string__()
        let __promiseHolder = bridge.wrap_std__shared_ptr_Promise_std__string__(__promise)
        __result
          .then({ __result in __promiseHolder.resolve(std.string(__result)) })
          .catch({ __error in __promiseHolder.reject(__error.toCpp()) })
        return __promise
      }()
      return bridge.create_Result_std__shared_ptr_Promise_std__string___(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_std__shared_ptr_Promise_std__string___(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getCarrierSync() -> bridge.Result_std__string_ {
    do {
      let __result = try self.__implementation.getCarrierSync()
      let __resultCpp = std.string(__result)
      return bridge.create_Result_std__string_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_std__string_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func isHeadphonesConnected() -> bridge.Result_std__shared_ptr_Promise_bool___ {
    do {
      let __result = try self.__implementation.isHeadphonesConnected()
      let __resultCpp = { () -> bridge.std__shared_ptr_Promise_bool__ in
        let __promise = bridge.create_std__shared_ptr_Promise_bool__()
        let __promiseHolder = bridge.wrap_std__shared_ptr_Promise_bool__(__promise)
        __result
          .then({ __result in __promiseHolder.resolve(__result) })
          .catch({ __error in __promiseHolder.reject(__error.toCpp()) })
        return __promise
      }()
      return bridge.create_Result_std__shared_ptr_Promise_bool___(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_std__shared_ptr_Promise_bool___(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getIsHeadphonesConnected() -> bridge.Result_bool_ {
    do {
      let __result = try self.__implementation.getIsHeadphonesConnected()
      let __resultCpp = __result
      return bridge.create_Result_bool_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_bool_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getIsWiredHeadphonesConnected() -> bridge.Result_bool_ {
    do {
      let __result = try self.__implementation.getIsWiredHeadphonesConnected()
      let __resultCpp = __result
      return bridge.create_Result_bool_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_bool_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getIsBluetoothHeadphonesConnected() -> bridge.Result_bool_ {
    do {
      let __result = try self.__implementation.getIsBluetoothHeadphonesConnected()
      let __resultCpp = __result
      return bridge.create_Result_bool_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_bool_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func isLocationEnabled() -> bridge.Result_std__shared_ptr_Promise_bool___ {
    do {
      let __result = try self.__implementation.isLocationEnabled()
      let __resultCpp = { () -> bridge.std__shared_ptr_Promise_bool__ in
        let __promise = bridge.create_std__shared_ptr_Promise_bool__()
        let __promiseHolder = bridge.wrap_std__shared_ptr_Promise_bool__(__promise)
        __result
          .then({ __result in __promiseHolder.resolve(__result) })
          .catch({ __error in __promiseHolder.reject(__error.toCpp()) })
        return __promise
      }()
      return bridge.create_Result_std__shared_ptr_Promise_bool___(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_std__shared_ptr_Promise_bool___(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getIsLocationEnabled() -> bridge.Result_bool_ {
    do {
      let __result = try self.__implementation.getIsLocationEnabled()
      let __resultCpp = __result
      return bridge.create_Result_bool_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_bool_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getAvailableLocationProviders() -> bridge.Result_std__vector_std__string__ {
    do {
      let __result = try self.__implementation.getAvailableLocationProviders()
      let __resultCpp = { () -> bridge.std__vector_std__string_ in
        var __vector = bridge.create_std__vector_std__string_(__result.count)
        for __item in __result {
          __vector.push_back(std.string(__item))
        }
        return __vector
      }()
      return bridge.create_Result_std__vector_std__string__(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_std__vector_std__string__(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getHasGms() -> bridge.Result_bool_ {
    do {
      let __result = try self.__implementation.getHasGms()
      let __resultCpp = __result
      return bridge.create_Result_bool_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_bool_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getHasHms() -> bridge.Result_bool_ {
    do {
      let __result = try self.__implementation.getHasHms()
      let __resultCpp = __result
      return bridge.create_Result_bool_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_bool_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func hasSystemFeature(feature: std.string) -> bridge.Result_bool_ {
    do {
      let __result = try self.__implementation.hasSystemFeature(feature: String(feature))
      let __resultCpp = __result
      return bridge.create_Result_bool_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_bool_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getDeviceToken() -> bridge.Result_std__shared_ptr_Promise_std__string___ {
    do {
      let __result = try self.__implementation.getDeviceToken()
      let __resultCpp = { () -> bridge.std__shared_ptr_Promise_std__string__ in
        let __promise = bridge.create_std__shared_ptr_Promise_std__string__()
        let __promiseHolder = bridge.wrap_std__shared_ptr_Promise_std__string__(__promise)
        __result
          .then({ __result in __promiseHolder.resolve(std.string(__result)) })
          .catch({ __error in __promiseHolder.reject(__error.toCpp()) })
        return __promise
      }()
      return bridge.create_Result_std__shared_ptr_Promise_std__string___(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_std__shared_ptr_Promise_std__string___(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func syncUniqueId() -> bridge.Result_std__shared_ptr_Promise_std__string___ {
    do {
      let __result = try self.__implementation.syncUniqueId()
      let __resultCpp = { () -> bridge.std__shared_ptr_Promise_std__string__ in
        let __promise = bridge.create_std__shared_ptr_Promise_std__string__()
        let __promiseHolder = bridge.wrap_std__shared_ptr_Promise_std__string__(__promise)
        __result
          .then({ __result in __promiseHolder.resolve(std.string(__result)) })
          .catch({ __error in __promiseHolder.reject(__error.toCpp()) })
        return __promise
      }()
      return bridge.create_Result_std__shared_ptr_Promise_std__string___(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_std__shared_ptr_Promise_std__string___(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getInstallReferrer() -> bridge.Result_std__shared_ptr_Promise_std__string___ {
    do {
      let __result = try self.__implementation.getInstallReferrer()
      let __resultCpp = { () -> bridge.std__shared_ptr_Promise_std__string__ in
        let __promise = bridge.create_std__shared_ptr_Promise_std__string__()
        let __promiseHolder = bridge.wrap_std__shared_ptr_Promise_std__string__(__promise)
        __result
          .then({ __result in __promiseHolder.resolve(std.string(__result)) })
          .catch({ __error in __promiseHolder.reject(__error.toCpp()) })
        return __promise
      }()
      return bridge.create_Result_std__shared_ptr_Promise_std__string___(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_std__shared_ptr_Promise_std__string___(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func isSideLoadingEnabled() -> bridge.Result_bool_ {
    do {
      let __result = try self.__implementation.isSideLoadingEnabled()
      let __resultCpp = __result
      return bridge.create_Result_bool_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_bool_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func getFreeDiskStorageOld() -> bridge.Result_double_ {
    do {
      let __result = try self.__implementation.getFreeDiskStorageOld()
      let __resultCpp = __result
      return bridge.create_Result_double_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_double_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func isDeviceCompromised() -> bridge.Result_bool_ {
    do {
      let __result = try self.__implementation.isDeviceCompromised()
      let __resultCpp = __result
      return bridge.create_Result_bool_(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_bool_(__exceptionPtr)
    }
  }
  
  @inline(__always)
  public final func verifyDeviceIntegrity() -> bridge.Result_std__shared_ptr_Promise_bool___ {
    do {
      let __result = try self.__implementation.verifyDeviceIntegrity()
      let __resultCpp = { () -> bridge.std__shared_ptr_Promise_bool__ in
        let __promise = bridge.create_std__shared_ptr_Promise_bool__()
        let __promiseHolder = bridge.wrap_std__shared_ptr_Promise_bool__(__promise)
        __result
          .then({ __result in __promiseHolder.resolve(__result) })
          .catch({ __error in __promiseHolder.reject(__error.toCpp()) })
        return __promise
      }()
      return bridge.create_Result_std__shared_ptr_Promise_bool___(__resultCpp)
    } catch (let __error) {
      let __exceptionPtr = __error.toCpp()
      return bridge.create_Result_std__shared_ptr_Promise_bool___(__exceptionPtr)
    }
  }
}
