///
/// NavigationMode.swift
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

/**
 * Represents the JS union `NavigationMode`, backed by a C++ enum.
 */
public typealias NavigationMode = margelo.nitro.nitrodeviceinfo.NavigationMode

public extension NavigationMode {
  /**
   * Get a NavigationMode for the given String value, or
   * return `nil` if the given value was invalid/unknown.
   */
  init?(fromString string: String) {
    switch string {
      case "unknown":
        self = .unknown
      case "gesture":
        self = .gesture
      case "buttons":
        self = .buttons
      case "twobuttons":
        self = .twobuttons
      default:
        return nil
    }
  }

  /**
   * Get the String value this NavigationMode represents.
   */
  var stringValue: String {
    switch self {
      case .unknown:
        return "unknown"
      case .gesture:
        return "gesture"
      case .buttons:
        return "buttons"
      case .twobuttons:
        return "twobuttons"
    }
  }
}
