///
/// PowerState.swift
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

import Foundation
import NitroModules

/**
 * Represents an instance of `PowerState`, backed by a C++ struct.
 */
public typealias PowerState = margelo.nitro.nitrodeviceinfo.PowerState

public extension PowerState {
  private typealias bridge = margelo.nitro.nitrodeviceinfo.bridge.swift

  /**
   * Create a new instance of `PowerState`.
   */
  init(batteryLevel: Double, batteryState: BatteryState, lowPowerMode: Bool) {
    self.init(batteryLevel, batteryState, lowPowerMode)
  }

  @inline(__always)
  var batteryLevel: Double {
    return self.__batteryLevel
  }
  
  @inline(__always)
  var batteryState: BatteryState {
    return self.__batteryState
  }
  
  @inline(__always)
  var lowPowerMode: Bool {
    return self.__lowPowerMode
  }
}
