///
/// DeviceType.hpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#pragma once

#if __has_include(<NitroModules/NitroHash.hpp>)
#include <NitroModules/NitroHash.hpp>
#else
#error NitroModules cannot be found! Are you sure you installed NitroModules properly?
#endif
#if __has_include(<NitroModules/JSIConverter.hpp>)
#include <NitroModules/JSIConverter.hpp>
#else
#error NitroModules cannot be found! Are you sure you installed NitroModules properly?
#endif
#if __has_include(<NitroModules/NitroDefines.hpp>)
#include <NitroModules/NitroDefines.hpp>
#else
#error NitroModules cannot be found! Are you sure you installed NitroModules properly?
#endif

namespace margelo::nitro::nitrodeviceinfo {

  /**
   * An enum which can be represented as a JavaScript union (DeviceType).
   */
  enum class DeviceType {
    HANDSET      SWIFT_NAME(handset) = 0,
    TABLET      SWIFT_NAME(tablet) = 1,
    TV      SWIFT_NAME(tv) = 2,
    DESKTOP      SWIFT_NAME(desktop) = 3,
    GAMINGCONSOLE      SWIFT_NAME(gamingconsole) = 4,
    UNKNOWN      SWIFT_NAME(unknown) = 5,
  } CLOSED_ENUM;

} // namespace margelo::nitro::nitrodeviceinfo

namespace margelo::nitro {

  // C++ DeviceType <> JS DeviceType (union)
  template <>
  struct JSIConverter<margelo::nitro::nitrodeviceinfo::DeviceType> final {
    static inline margelo::nitro::nitrodeviceinfo::DeviceType fromJSI(jsi::Runtime& runtime, const jsi::Value& arg) {
      std::string unionValue = JSIConverter<std::string>::fromJSI(runtime, arg);
      switch (hashString(unionValue.c_str(), unionValue.size())) {
        case hashString("Handset"): return margelo::nitro::nitrodeviceinfo::DeviceType::HANDSET;
        case hashString("Tablet"): return margelo::nitro::nitrodeviceinfo::DeviceType::TABLET;
        case hashString("Tv"): return margelo::nitro::nitrodeviceinfo::DeviceType::TV;
        case hashString("Desktop"): return margelo::nitro::nitrodeviceinfo::DeviceType::DESKTOP;
        case hashString("GamingConsole"): return margelo::nitro::nitrodeviceinfo::DeviceType::GAMINGCONSOLE;
        case hashString("unknown"): return margelo::nitro::nitrodeviceinfo::DeviceType::UNKNOWN;
        default: [[unlikely]]
          throw std::invalid_argument("Cannot convert \"" + unionValue + "\" to enum DeviceType - invalid value!");
      }
    }
    static inline jsi::Value toJSI(jsi::Runtime& runtime, margelo::nitro::nitrodeviceinfo::DeviceType arg) {
      switch (arg) {
        case margelo::nitro::nitrodeviceinfo::DeviceType::HANDSET: return JSIConverter<std::string>::toJSI(runtime, "Handset");
        case margelo::nitro::nitrodeviceinfo::DeviceType::TABLET: return JSIConverter<std::string>::toJSI(runtime, "Tablet");
        case margelo::nitro::nitrodeviceinfo::DeviceType::TV: return JSIConverter<std::string>::toJSI(runtime, "Tv");
        case margelo::nitro::nitrodeviceinfo::DeviceType::DESKTOP: return JSIConverter<std::string>::toJSI(runtime, "Desktop");
        case margelo::nitro::nitrodeviceinfo::DeviceType::GAMINGCONSOLE: return JSIConverter<std::string>::toJSI(runtime, "GamingConsole");
        case margelo::nitro::nitrodeviceinfo::DeviceType::UNKNOWN: return JSIConverter<std::string>::toJSI(runtime, "unknown");
        default: [[unlikely]]
          throw std::invalid_argument("Cannot convert DeviceType to JS - invalid value: "
                                    + std::to_string(static_cast<int>(arg)) + "!");
      }
    }
    static inline bool canConvert(jsi::Runtime& runtime, const jsi::Value& value) {
      if (!value.isString()) {
        return false;
      }
      std::string unionValue = JSIConverter<std::string>::fromJSI(runtime, value);
      switch (hashString(unionValue.c_str(), unionValue.size())) {
        case hashString("Handset"):
        case hashString("Tablet"):
        case hashString("Tv"):
        case hashString("Desktop"):
        case hashString("GamingConsole"):
        case hashString("unknown"):
          return true;
        default:
          return false;
      }
    }
  };

} // namespace margelo::nitro
