///
/// HybridDeviceInfoSpec.hpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#pragma once

#if __has_include(<NitroModules/HybridObject.hpp>)
#include <NitroModules/HybridObject.hpp>
#else
#error NitroModules cannot be found! Are you sure you installed NitroModules properly?
#endif

// Forward declaration of `DeviceType` to properly resolve imports.
namespace margelo::nitro::nitrodeviceinfo { enum class DeviceType; }
// Forward declaration of `NavigationMode` to properly resolve imports.
namespace margelo::nitro::nitrodeviceinfo { enum class NavigationMode; }
// Forward declaration of `PowerState` to properly resolve imports.
namespace margelo::nitro::nitrodeviceinfo { struct PowerState; }

#include <string>
#include "DeviceType.hpp"
#include <vector>
#include "NavigationMode.hpp"
#include "PowerState.hpp"
#include <NitroModules/Promise.hpp>

namespace margelo::nitro::nitrodeviceinfo {

  using namespace margelo::nitro;

  /**
   * An abstract base class for `DeviceInfo`
   * Inherit this class to create instances of `HybridDeviceInfoSpec` in C++.
   * You must explicitly call `HybridObject`'s constructor yourself, because it is virtual.
   * @example
   * ```cpp
   * class HybridDeviceInfo: public HybridDeviceInfoSpec {
   * public:
   *   HybridDeviceInfo(...): HybridObject(TAG) { ... }
   *   // ...
   * };
   * ```
   */
  class HybridDeviceInfoSpec: public virtual HybridObject {
    public:
      // Constructor
      explicit HybridDeviceInfoSpec(): HybridObject(TAG) { }

      // Destructor
      ~HybridDeviceInfoSpec() override = default;

    public:
      // Properties
      virtual std::string getDeviceId() = 0;
      virtual std::string getBrand() = 0;
      virtual std::string getModel() = 0;
      virtual std::string getSystemName() = 0;
      virtual std::string getSystemVersion() = 0;
      virtual DeviceType getDeviceType() = 0;
      virtual std::string getUniqueId() = 0;
      virtual std::string getManufacturer() = 0;
      virtual std::string getDeviceName() = 0;
      virtual bool getIsTablet() = 0;
      virtual bool getIsEmulator() = 0;
      virtual double getDeviceYearClass() = 0;
      virtual bool getIsCameraPresent() = 0;
      virtual bool getIsPinOrFingerprintSet() = 0;
      virtual bool getIsHardwareKeyStoreAvailable() = 0;
      virtual bool getIsLowRamDevice() = 0;
      virtual bool getIsDisplayZoomed() = 0;
      virtual bool getIsLiquidGlassAvailable() = 0;
      virtual double getTotalMemory() = 0;
      virtual double getMaxMemory() = 0;
      virtual double getTotalDiskCapacity() = 0;
      virtual double getStartupTime() = 0;
      virtual std::string getVersion() = 0;
      virtual std::string getBuildNumber() = 0;
      virtual std::string getBundleId() = 0;
      virtual std::string getApplicationName() = 0;
      virtual std::string getReadableVersion() = 0;
      virtual double getFirstInstallTimeSync() = 0;
      virtual double getLastUpdateTimeSync() = 0;
      virtual bool getCarrierAllowsVOIP() = 0;
      virtual std::string getCarrierIsoCountryCode() = 0;
      virtual std::string getMobileCountryCode() = 0;
      virtual std::string getMobileNetworkCode() = 0;
      virtual std::string getMobileNetworkOperator() = 0;
      virtual std::string getSystemLanguage() = 0;
      virtual std::vector<std::string> getSupportedAbis() = 0;
      virtual std::vector<std::string> getSupported32BitAbis() = 0;
      virtual std::vector<std::string> getSupported64BitAbis() = 0;
      virtual double getApiLevel() = 0;
      virtual NavigationMode getNavigationMode() = 0;
      virtual std::vector<std::string> getSystemAvailableFeatures() = 0;
      virtual std::vector<std::string> getSupportedMediaTypeList() = 0;
      virtual std::string getSerialNumber() = 0;
      virtual std::string getAndroidId() = 0;
      virtual double getPreviewSdkInt() = 0;
      virtual std::string getSecurityPatch() = 0;
      virtual std::string getCodename() = 0;
      virtual std::string getIncremental() = 0;
      virtual std::string getBoard() = 0;
      virtual std::string getBootloader() = 0;
      virtual std::string getDevice() = 0;
      virtual std::string getDisplay() = 0;
      virtual std::string getFingerprint() = 0;
      virtual std::string getHardware() = 0;
      virtual std::string getHost() = 0;
      virtual std::string getProduct() = 0;
      virtual std::string getTags() = 0;
      virtual std::string getType() = 0;
      virtual std::string getBaseOs() = 0;
      virtual std::string getRadioVersion() = 0;
      virtual std::string getBuildId() = 0;
      virtual std::string getInstallerPackageName() = 0;
      virtual double getTotalDiskCapacityOld() = 0;
      virtual bool getIsMouseConnected() = 0;
      virtual bool getIsKeyboardConnected() = 0;
      virtual std::vector<std::string> getHostNames() = 0;
      virtual bool getIsTabletMode() = 0;

    public:
      // Methods
      virtual bool getHasNotch() = 0;
      virtual bool getHasDynamicIsland() = 0;
      virtual bool getIsLandscape() = 0;
      virtual double getBrightness() = 0;
      virtual double getFontScale() = 0;
      virtual double getUsedMemory() = 0;
      virtual double getFreeDiskStorage() = 0;
      virtual double getUptime() = 0;
      virtual double getBatteryLevel() = 0;
      virtual PowerState getPowerState() = 0;
      virtual bool getIsBatteryCharging() = 0;
      virtual bool isLowBatteryLevel(double threshold) = 0;
      virtual std::shared_ptr<Promise<double>> getFirstInstallTime() = 0;
      virtual std::shared_ptr<Promise<double>> getLastUpdateTime() = 0;
      virtual std::shared_ptr<Promise<std::string>> getIpAddress() = 0;
      virtual std::string getIpAddressSync() = 0;
      virtual std::shared_ptr<Promise<std::string>> getMacAddress() = 0;
      virtual std::string getMacAddressSync() = 0;
      virtual std::shared_ptr<Promise<std::string>> getUserAgent() = 0;
      virtual bool getIsAirplaneMode() = 0;
      virtual std::shared_ptr<Promise<std::string>> getCarrier() = 0;
      virtual std::string getCarrierSync() = 0;
      virtual std::shared_ptr<Promise<bool>> isHeadphonesConnected() = 0;
      virtual bool getIsHeadphonesConnected() = 0;
      virtual bool getIsWiredHeadphonesConnected() = 0;
      virtual bool getIsBluetoothHeadphonesConnected() = 0;
      virtual std::shared_ptr<Promise<bool>> isLocationEnabled() = 0;
      virtual bool getIsLocationEnabled() = 0;
      virtual std::vector<std::string> getAvailableLocationProviders() = 0;
      virtual bool getHasGms() = 0;
      virtual bool getHasHms() = 0;
      virtual bool hasSystemFeature(const std::string& feature) = 0;
      virtual std::shared_ptr<Promise<std::string>> getDeviceToken() = 0;
      virtual std::shared_ptr<Promise<std::string>> syncUniqueId() = 0;
      virtual std::shared_ptr<Promise<std::string>> getInstallReferrer() = 0;
      virtual bool isSideLoadingEnabled() = 0;
      virtual double getFreeDiskStorageOld() = 0;
      virtual bool isDeviceCompromised() = 0;
      virtual std::shared_ptr<Promise<bool>> verifyDeviceIntegrity() = 0;

    protected:
      // Hybrid Setup
      void loadHybridMethods() override;

    protected:
      // Tag for logging
      static constexpr auto TAG = "DeviceInfo";
  };

} // namespace margelo::nitro::nitrodeviceinfo
