///
/// HybridDeviceInfoSpec.cpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#include "HybridDeviceInfoSpec.hpp"

namespace margelo::nitro::nitrodeviceinfo {

  void HybridDeviceInfoSpec::loadHybridMethods() {
    // load base methods/properties
    HybridObject::loadHybridMethods();
    // load custom methods/properties
    registerHybrids(this, [](Prototype& prototype) {
      prototype.registerHybridGetter("deviceId", &HybridDeviceInfoSpec::getDeviceId);
      prototype.registerHybridGetter("brand", &HybridDeviceInfoSpec::getBrand);
      prototype.registerHybridGetter("model", &HybridDeviceInfoSpec::getModel);
      prototype.registerHybridGetter("systemName", &HybridDeviceInfoSpec::getSystemName);
      prototype.registerHybridGetter("systemVersion", &HybridDeviceInfoSpec::getSystemVersion);
      prototype.registerHybridGetter("deviceType", &HybridDeviceInfoSpec::getDeviceType);
      prototype.registerHybridGetter("uniqueId", &HybridDeviceInfoSpec::getUniqueId);
      prototype.registerHybridGetter("manufacturer", &HybridDeviceInfoSpec::getManufacturer);
      prototype.registerHybridGetter("deviceName", &HybridDeviceInfoSpec::getDeviceName);
      prototype.registerHybridGetter("isTablet", &HybridDeviceInfoSpec::getIsTablet);
      prototype.registerHybridGetter("isEmulator", &HybridDeviceInfoSpec::getIsEmulator);
      prototype.registerHybridGetter("deviceYearClass", &HybridDeviceInfoSpec::getDeviceYearClass);
      prototype.registerHybridGetter("isCameraPresent", &HybridDeviceInfoSpec::getIsCameraPresent);
      prototype.registerHybridGetter("isPinOrFingerprintSet", &HybridDeviceInfoSpec::getIsPinOrFingerprintSet);
      prototype.registerHybridGetter("isHardwareKeyStoreAvailable", &HybridDeviceInfoSpec::getIsHardwareKeyStoreAvailable);
      prototype.registerHybridGetter("isLowRamDevice", &HybridDeviceInfoSpec::getIsLowRamDevice);
      prototype.registerHybridGetter("isDisplayZoomed", &HybridDeviceInfoSpec::getIsDisplayZoomed);
      prototype.registerHybridGetter("isLiquidGlassAvailable", &HybridDeviceInfoSpec::getIsLiquidGlassAvailable);
      prototype.registerHybridGetter("totalMemory", &HybridDeviceInfoSpec::getTotalMemory);
      prototype.registerHybridGetter("maxMemory", &HybridDeviceInfoSpec::getMaxMemory);
      prototype.registerHybridGetter("totalDiskCapacity", &HybridDeviceInfoSpec::getTotalDiskCapacity);
      prototype.registerHybridGetter("startupTime", &HybridDeviceInfoSpec::getStartupTime);
      prototype.registerHybridGetter("version", &HybridDeviceInfoSpec::getVersion);
      prototype.registerHybridGetter("buildNumber", &HybridDeviceInfoSpec::getBuildNumber);
      prototype.registerHybridGetter("bundleId", &HybridDeviceInfoSpec::getBundleId);
      prototype.registerHybridGetter("applicationName", &HybridDeviceInfoSpec::getApplicationName);
      prototype.registerHybridGetter("readableVersion", &HybridDeviceInfoSpec::getReadableVersion);
      prototype.registerHybridGetter("firstInstallTimeSync", &HybridDeviceInfoSpec::getFirstInstallTimeSync);
      prototype.registerHybridGetter("lastUpdateTimeSync", &HybridDeviceInfoSpec::getLastUpdateTimeSync);
      prototype.registerHybridGetter("carrierAllowsVOIP", &HybridDeviceInfoSpec::getCarrierAllowsVOIP);
      prototype.registerHybridGetter("carrierIsoCountryCode", &HybridDeviceInfoSpec::getCarrierIsoCountryCode);
      prototype.registerHybridGetter("mobileCountryCode", &HybridDeviceInfoSpec::getMobileCountryCode);
      prototype.registerHybridGetter("mobileNetworkCode", &HybridDeviceInfoSpec::getMobileNetworkCode);
      prototype.registerHybridGetter("mobileNetworkOperator", &HybridDeviceInfoSpec::getMobileNetworkOperator);
      prototype.registerHybridGetter("systemLanguage", &HybridDeviceInfoSpec::getSystemLanguage);
      prototype.registerHybridGetter("supportedAbis", &HybridDeviceInfoSpec::getSupportedAbis);
      prototype.registerHybridGetter("supported32BitAbis", &HybridDeviceInfoSpec::getSupported32BitAbis);
      prototype.registerHybridGetter("supported64BitAbis", &HybridDeviceInfoSpec::getSupported64BitAbis);
      prototype.registerHybridGetter("apiLevel", &HybridDeviceInfoSpec::getApiLevel);
      prototype.registerHybridGetter("navigationMode", &HybridDeviceInfoSpec::getNavigationMode);
      prototype.registerHybridGetter("systemAvailableFeatures", &HybridDeviceInfoSpec::getSystemAvailableFeatures);
      prototype.registerHybridGetter("supportedMediaTypeList", &HybridDeviceInfoSpec::getSupportedMediaTypeList);
      prototype.registerHybridGetter("serialNumber", &HybridDeviceInfoSpec::getSerialNumber);
      prototype.registerHybridGetter("androidId", &HybridDeviceInfoSpec::getAndroidId);
      prototype.registerHybridGetter("previewSdkInt", &HybridDeviceInfoSpec::getPreviewSdkInt);
      prototype.registerHybridGetter("securityPatch", &HybridDeviceInfoSpec::getSecurityPatch);
      prototype.registerHybridGetter("codename", &HybridDeviceInfoSpec::getCodename);
      prototype.registerHybridGetter("incremental", &HybridDeviceInfoSpec::getIncremental);
      prototype.registerHybridGetter("board", &HybridDeviceInfoSpec::getBoard);
      prototype.registerHybridGetter("bootloader", &HybridDeviceInfoSpec::getBootloader);
      prototype.registerHybridGetter("device", &HybridDeviceInfoSpec::getDevice);
      prototype.registerHybridGetter("display", &HybridDeviceInfoSpec::getDisplay);
      prototype.registerHybridGetter("fingerprint", &HybridDeviceInfoSpec::getFingerprint);
      prototype.registerHybridGetter("hardware", &HybridDeviceInfoSpec::getHardware);
      prototype.registerHybridGetter("host", &HybridDeviceInfoSpec::getHost);
      prototype.registerHybridGetter("product", &HybridDeviceInfoSpec::getProduct);
      prototype.registerHybridGetter("tags", &HybridDeviceInfoSpec::getTags);
      prototype.registerHybridGetter("type", &HybridDeviceInfoSpec::getType);
      prototype.registerHybridGetter("baseOs", &HybridDeviceInfoSpec::getBaseOs);
      prototype.registerHybridGetter("radioVersion", &HybridDeviceInfoSpec::getRadioVersion);
      prototype.registerHybridGetter("buildId", &HybridDeviceInfoSpec::getBuildId);
      prototype.registerHybridGetter("installerPackageName", &HybridDeviceInfoSpec::getInstallerPackageName);
      prototype.registerHybridGetter("totalDiskCapacityOld", &HybridDeviceInfoSpec::getTotalDiskCapacityOld);
      prototype.registerHybridGetter("isMouseConnected", &HybridDeviceInfoSpec::getIsMouseConnected);
      prototype.registerHybridGetter("isKeyboardConnected", &HybridDeviceInfoSpec::getIsKeyboardConnected);
      prototype.registerHybridGetter("hostNames", &HybridDeviceInfoSpec::getHostNames);
      prototype.registerHybridGetter("isTabletMode", &HybridDeviceInfoSpec::getIsTabletMode);
      prototype.registerHybridMethod("getHasNotch", &HybridDeviceInfoSpec::getHasNotch);
      prototype.registerHybridMethod("getHasDynamicIsland", &HybridDeviceInfoSpec::getHasDynamicIsland);
      prototype.registerHybridMethod("getIsLandscape", &HybridDeviceInfoSpec::getIsLandscape);
      prototype.registerHybridMethod("getBrightness", &HybridDeviceInfoSpec::getBrightness);
      prototype.registerHybridMethod("getFontScale", &HybridDeviceInfoSpec::getFontScale);
      prototype.registerHybridMethod("getUsedMemory", &HybridDeviceInfoSpec::getUsedMemory);
      prototype.registerHybridMethod("getFreeDiskStorage", &HybridDeviceInfoSpec::getFreeDiskStorage);
      prototype.registerHybridMethod("getUptime", &HybridDeviceInfoSpec::getUptime);
      prototype.registerHybridMethod("getBatteryLevel", &HybridDeviceInfoSpec::getBatteryLevel);
      prototype.registerHybridMethod("getPowerState", &HybridDeviceInfoSpec::getPowerState);
      prototype.registerHybridMethod("getIsBatteryCharging", &HybridDeviceInfoSpec::getIsBatteryCharging);
      prototype.registerHybridMethod("isLowBatteryLevel", &HybridDeviceInfoSpec::isLowBatteryLevel);
      prototype.registerHybridMethod("getFirstInstallTime", &HybridDeviceInfoSpec::getFirstInstallTime);
      prototype.registerHybridMethod("getLastUpdateTime", &HybridDeviceInfoSpec::getLastUpdateTime);
      prototype.registerHybridMethod("getIpAddress", &HybridDeviceInfoSpec::getIpAddress);
      prototype.registerHybridMethod("getIpAddressSync", &HybridDeviceInfoSpec::getIpAddressSync);
      prototype.registerHybridMethod("getMacAddress", &HybridDeviceInfoSpec::getMacAddress);
      prototype.registerHybridMethod("getMacAddressSync", &HybridDeviceInfoSpec::getMacAddressSync);
      prototype.registerHybridMethod("getUserAgent", &HybridDeviceInfoSpec::getUserAgent);
      prototype.registerHybridMethod("getIsAirplaneMode", &HybridDeviceInfoSpec::getIsAirplaneMode);
      prototype.registerHybridMethod("getCarrier", &HybridDeviceInfoSpec::getCarrier);
      prototype.registerHybridMethod("getCarrierSync", &HybridDeviceInfoSpec::getCarrierSync);
      prototype.registerHybridMethod("isHeadphonesConnected", &HybridDeviceInfoSpec::isHeadphonesConnected);
      prototype.registerHybridMethod("getIsHeadphonesConnected", &HybridDeviceInfoSpec::getIsHeadphonesConnected);
      prototype.registerHybridMethod("getIsWiredHeadphonesConnected", &HybridDeviceInfoSpec::getIsWiredHeadphonesConnected);
      prototype.registerHybridMethod("getIsBluetoothHeadphonesConnected", &HybridDeviceInfoSpec::getIsBluetoothHeadphonesConnected);
      prototype.registerHybridMethod("isLocationEnabled", &HybridDeviceInfoSpec::isLocationEnabled);
      prototype.registerHybridMethod("getIsLocationEnabled", &HybridDeviceInfoSpec::getIsLocationEnabled);
      prototype.registerHybridMethod("getAvailableLocationProviders", &HybridDeviceInfoSpec::getAvailableLocationProviders);
      prototype.registerHybridMethod("getHasGms", &HybridDeviceInfoSpec::getHasGms);
      prototype.registerHybridMethod("getHasHms", &HybridDeviceInfoSpec::getHasHms);
      prototype.registerHybridMethod("hasSystemFeature", &HybridDeviceInfoSpec::hasSystemFeature);
      prototype.registerHybridMethod("getDeviceToken", &HybridDeviceInfoSpec::getDeviceToken);
      prototype.registerHybridMethod("syncUniqueId", &HybridDeviceInfoSpec::syncUniqueId);
      prototype.registerHybridMethod("getInstallReferrer", &HybridDeviceInfoSpec::getInstallReferrer);
      prototype.registerHybridMethod("isSideLoadingEnabled", &HybridDeviceInfoSpec::isSideLoadingEnabled);
      prototype.registerHybridMethod("getFreeDiskStorageOld", &HybridDeviceInfoSpec::getFreeDiskStorageOld);
      prototype.registerHybridMethod("isDeviceCompromised", &HybridDeviceInfoSpec::isDeviceCompromised);
      prototype.registerHybridMethod("verifyDeviceIntegrity", &HybridDeviceInfoSpec::verifyDeviceIntegrity);
    });
  }

} // namespace margelo::nitro::nitrodeviceinfo
