///
/// NavigationMode.hpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#pragma once

#if __has_include(<NitroModules/NitroHash.hpp>)
#include <NitroModules/NitroHash.hpp>
#else
#error NitroModules cannot be found! Are you sure you installed NitroModules properly?
#endif
#if __has_include(<NitroModules/JSIConverter.hpp>)
#include <NitroModules/JSIConverter.hpp>
#else
#error NitroModules cannot be found! Are you sure you installed NitroModules properly?
#endif
#if __has_include(<NitroModules/NitroDefines.hpp>)
#include <NitroModules/NitroDefines.hpp>
#else
#error NitroModules cannot be found! Are you sure you installed NitroModules properly?
#endif

namespace margelo::nitro::nitrodeviceinfo {

  /**
   * An enum which can be represented as a JavaScript union (NavigationMode).
   */
  enum class NavigationMode {
    UNKNOWN      SWIFT_NAME(unknown) = 0,
    GESTURE      SWIFT_NAME(gesture) = 1,
    BUTTONS      SWIFT_NAME(buttons) = 2,
    TWOBUTTONS      SWIFT_NAME(twobuttons) = 3,
  } CLOSED_ENUM;

} // namespace margelo::nitro::nitrodeviceinfo

namespace margelo::nitro {

  // C++ NavigationMode <> JS NavigationMode (union)
  template <>
  struct JSIConverter<margelo::nitro::nitrodeviceinfo::NavigationMode> final {
    static inline margelo::nitro::nitrodeviceinfo::NavigationMode fromJSI(jsi::Runtime& runtime, const jsi::Value& arg) {
      std::string unionValue = JSIConverter<std::string>::fromJSI(runtime, arg);
      switch (hashString(unionValue.c_str(), unionValue.size())) {
        case hashString("unknown"): return margelo::nitro::nitrodeviceinfo::NavigationMode::UNKNOWN;
        case hashString("gesture"): return margelo::nitro::nitrodeviceinfo::NavigationMode::GESTURE;
        case hashString("buttons"): return margelo::nitro::nitrodeviceinfo::NavigationMode::BUTTONS;
        case hashString("twobuttons"): return margelo::nitro::nitrodeviceinfo::NavigationMode::TWOBUTTONS;
        default: [[unlikely]]
          throw std::invalid_argument("Cannot convert \"" + unionValue + "\" to enum NavigationMode - invalid value!");
      }
    }
    static inline jsi::Value toJSI(jsi::Runtime& runtime, margelo::nitro::nitrodeviceinfo::NavigationMode arg) {
      switch (arg) {
        case margelo::nitro::nitrodeviceinfo::NavigationMode::UNKNOWN: return JSIConverter<std::string>::toJSI(runtime, "unknown");
        case margelo::nitro::nitrodeviceinfo::NavigationMode::GESTURE: return JSIConverter<std::string>::toJSI(runtime, "gesture");
        case margelo::nitro::nitrodeviceinfo::NavigationMode::BUTTONS: return JSIConverter<std::string>::toJSI(runtime, "buttons");
        case margelo::nitro::nitrodeviceinfo::NavigationMode::TWOBUTTONS: return JSIConverter<std::string>::toJSI(runtime, "twobuttons");
        default: [[unlikely]]
          throw std::invalid_argument("Cannot convert NavigationMode to JS - invalid value: "
                                    + std::to_string(static_cast<int>(arg)) + "!");
      }
    }
    static inline bool canConvert(jsi::Runtime& runtime, const jsi::Value& value) {
      if (!value.isString()) {
        return false;
      }
      std::string unionValue = JSIConverter<std::string>::fromJSI(runtime, value);
      switch (hashString(unionValue.c_str(), unionValue.size())) {
        case hashString("unknown"):
        case hashString("gesture"):
        case hashString("buttons"):
        case hashString("twobuttons"):
          return true;
        default:
          return false;
      }
    }
  };

} // namespace margelo::nitro
