///
/// PowerState.hpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © Marc Rousavy @ Margelo
///

#pragma once

#if __has_include(<NitroModules/JSIConverter.hpp>)
#include <NitroModules/JSIConverter.hpp>
#else
#error NitroModules cannot be found! Are you sure you installed NitroModules properly?
#endif
#if __has_include(<NitroModules/NitroDefines.hpp>)
#include <NitroModules/NitroDefines.hpp>
#else
#error NitroModules cannot be found! Are you sure you installed NitroModules properly?
#endif
#if __has_include(<NitroModules/JSIHelpers.hpp>)
#include <NitroModules/JSIHelpers.hpp>
#else
#error NitroModules cannot be found! Are you sure you installed NitroModules properly?
#endif
#if __has_include(<NitroModules/PropNameIDCache.hpp>)
#include <NitroModules/PropNameIDCache.hpp>
#else
#error NitroModules cannot be found! Are you sure you installed NitroModules properly?
#endif

// Forward declaration of `BatteryState` to properly resolve imports.
namespace margelo::nitro::nitrodeviceinfo { enum class BatteryState; }

#include "BatteryState.hpp"

namespace margelo::nitro::nitrodeviceinfo {

  /**
   * A struct which can be represented as a JavaScript object (PowerState).
   */
  struct PowerState final {
  public:
    double batteryLevel     SWIFT_PRIVATE;
    BatteryState batteryState     SWIFT_PRIVATE;
    bool lowPowerMode     SWIFT_PRIVATE;

  public:
    PowerState() = default;
    explicit PowerState(double batteryLevel, BatteryState batteryState, bool lowPowerMode): batteryLevel(batteryLevel), batteryState(batteryState), lowPowerMode(lowPowerMode) {}

  public:
    friend bool operator==(const PowerState& lhs, const PowerState& rhs) = default;
  };

} // namespace margelo::nitro::nitrodeviceinfo

namespace margelo::nitro {

  // C++ PowerState <> JS PowerState (object)
  template <>
  struct JSIConverter<margelo::nitro::nitrodeviceinfo::PowerState> final {
    static inline margelo::nitro::nitrodeviceinfo::PowerState fromJSI(jsi::Runtime& runtime, const jsi::Value& arg) {
      jsi::Object obj = arg.asObject(runtime);
      return margelo::nitro::nitrodeviceinfo::PowerState(
        JSIConverter<double>::fromJSI(runtime, obj.getProperty(runtime, PropNameIDCache::get(runtime, "batteryLevel"))),
        JSIConverter<margelo::nitro::nitrodeviceinfo::BatteryState>::fromJSI(runtime, obj.getProperty(runtime, PropNameIDCache::get(runtime, "batteryState"))),
        JSIConverter<bool>::fromJSI(runtime, obj.getProperty(runtime, PropNameIDCache::get(runtime, "lowPowerMode")))
      );
    }
    static inline jsi::Value toJSI(jsi::Runtime& runtime, const margelo::nitro::nitrodeviceinfo::PowerState& arg) {
      jsi::Object obj(runtime);
      obj.setProperty(runtime, PropNameIDCache::get(runtime, "batteryLevel"), JSIConverter<double>::toJSI(runtime, arg.batteryLevel));
      obj.setProperty(runtime, PropNameIDCache::get(runtime, "batteryState"), JSIConverter<margelo::nitro::nitrodeviceinfo::BatteryState>::toJSI(runtime, arg.batteryState));
      obj.setProperty(runtime, PropNameIDCache::get(runtime, "lowPowerMode"), JSIConverter<bool>::toJSI(runtime, arg.lowPowerMode));
      return obj;
    }
    static inline bool canConvert(jsi::Runtime& runtime, const jsi::Value& value) {
      if (!value.isObject()) {
        return false;
      }
      jsi::Object obj = value.getObject(runtime);
      if (!nitro::isPlainObject(runtime, obj)) {
        return false;
      }
      if (!JSIConverter<double>::canConvert(runtime, obj.getProperty(runtime, PropNameIDCache::get(runtime, "batteryLevel")))) return false;
      if (!JSIConverter<margelo::nitro::nitrodeviceinfo::BatteryState>::canConvert(runtime, obj.getProperty(runtime, PropNameIDCache::get(runtime, "batteryState")))) return false;
      if (!JSIConverter<bool>::canConvert(runtime, obj.getProperty(runtime, PropNameIDCache::get(runtime, "lowPowerMode")))) return false;
      return true;
    }
  };

} // namespace margelo::nitro
